import Head from 'next/head'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contacts from '../components/Contact'

export default function Home() {
  return (
    <>
      <Head>
        <title>Artsiom Kunitsyn | Fullstack developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contacts />
    </>
  )
}
